### PR TITLE
Fix erase

### PR DESCRIPTION
**Pull request by Eirmas**

### CODE REVIEW

**Comment by NikoGrano** [comment]
#119 must be merged first!!! FYI for everyone.

**Comment by Eirmas** [comment]
Increased the hit stroke. This means tiny objects will be easier to erase cause you dont have to click directly at it, but can hit it with a 10 px margin

**Comment by Eirmas** [comment]
Here is an example of the code. The vuex state now updates on all clients through adding and removing objects from the canvas. Removed objects are pushed into the history array.
Synchronized vuex states

**Comment by Eirmas** [comment]
Sidenote: forgot to mention I converted rgba to hexa.

**Comment by bryansamuel1** [comment]
> Sidenote: forgot to mention I converted rgba to hexa.

@allforme3 does this effect you with the colour of your cursor?

**Pull request merged**
