### PR TITLE
Implement MVP1 - Nav. Remove shadows (GameTactic#189)

### LINKED ISSUE #189: MVP1 - Logo - Update Orange Colour

### PR DESCRIPTION
**Pull request by MightyWizard83**
closes #189 @NikoGrano

### CODE REVIEW

**Comment by NikoGrano** [comment]
Thanks :)

**Comment by NikoGrano** [comment]
Preview available: http://14798554-review-feature-18-jveup9.gametactic.eu

**Comment by bryansamuel1** [comment]
approved but we need to get your commits signed. I'll run through this with you this weekend if you want.

For now, @NikoGrano  can you bypass and get this merged in?

**Comment by NikoGrano** [comment]
Just squash and it gets signed...

**Pull request merged**
